### ISSUE TITLE
Only some pods fire in a fully loaded Transport Tank in some situations

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1151]
This seems to happen when attacking diagonally and when the target is outside its range.

This APC was loaded with 5 Machine Gun Pods, but this seems to happen with other pods too.

![Screenshot_20240817_110258_2](https://github.com/user-attachments/assets/7937ed30-bf9d-4cdb-ba37-f0525e6e5ea8)

**Comment by Mailaender** [comment]
Looking from the screenshot, this behavior makes sense to me.

**Comment by WilliamWeberBerrutti** [comment]
So, in a transport with 5 Machinegun pods, only 3 firing is intended? Shouldn't be all 5? This behavior is strange to me (thinking like Starcraft's Bunker, where all units inside can attack if the target is in range of all of them).

**Comment by GraionDilach** [comment]
Are they in range though?

I mean, OpenHV's AttackOpenTopped (and upstream AttackGarrisoned as well) will take the firing offset as part of the weapon's range. So if the firing offset adds up to the target distance (and in the screenshot, the last two slots does add to it), then that can be enough to push the target out of the passenger's range.

Note that this is less obvious with upstream AttackGarrisoned because AttackGarrisoned will always pick the closest available fireport for all the weapons, regardless of their passengers, resulting as if all the passengers can fire out from the same port at the same time. AttackOpenTopped assigns the ports out based on the passenger instead.

**Comment by WilliamWeberBerrutti** [comment]
I see. This pattern is still strange to me, maybe because I have Starcraft background, but I understand the reasoning. Maybe it needs some tweaks so all fireports have their visual positions preserved.

**Comment by GraionDilach** [comment]
I can understand where's that coming from. I mean, AttackGarrisoned would satisfy your gameplay expectation as-is, at the cost of introducing projectile stacking and sacrificing immersion and visual clarity. 

For a static bunker building (especially, if it has bigger than a 1x1 foundation), I would opt for mixing the behaviour of the two traits via defining individual garrison ports for each sides for all passengers, so that they can fire individually, yet prevent stacking (implying they have the room to just line up at a side). This would heavily decrease the chances of seeing this behaviour in action. (Note that AttackOpenTopped can't do this currently as-is.)

However, for a transport unit, I don't see this option feasible, simply because I don't think there's that much room for such an operation inside. IMO, having defined individual offsets to passengers can help though, if it comes to hardcounters (back to my YR strategies, I tended to position a Navy SEAL in front center and the other units behind it, because while the SEAL had the same range as most of the other infrantry, ensuring that the SEAL's instahit able to target enemy infantry first would mean they can hardcounter them before I manage to waste shots/overshoot by my other units).

**Comment by WilliamWeberBerrutti** [comment]
I see. So maybe it could remain the way it is currently.
