### ISSUE TITLE
Game crashed on load save

### ISSUE THREAD

**Issue by son-link** [OpenHV/OpenHV#360]
Hi, i download the lasted build (20210910), start a skirmish, save, but as soon as I click to load the game I get an error message and it closes. This is the content of the log file:
[exception-2021-09-12T095624Z.log](https://github.com/OpenHV/OpenHV/files/7149522/exception-2021-09-12T095624Z.log)

I use Arch Linux and i use the .AppImage

**Comment by Mailaender** [comment]
Did you try to load a game from a previous version?

**Comment by son-link** [comment]
I have tried several maps in this and the previous version (20210905) and so far it only seems to fail on some of them (with * the ones that also fail on the previous version):
Green Greens *
Beyond Destruction
Crescendo
Diminishing Results *
Clovergrief *
Tournament Island
Warbone
Waterbridgeworld
Sandy Shores
Another thing I've noticed is that the save files for these maps are 0 bytes, except for Green Greens (only on the current one) and Warbone.

Translated with www.DeepL.com/Translator (free version)

**Comment by Mailaender** [comment]
Works just fine here. We changed the maps in between the releases https://github.com/OpenHV/OpenHV/commit/885592bffdbc825bf083a421bb099d14286a4c1a so that may cause incompatibilities. The way the save feature works (replaying a demo at high speed) this can't be fixed. If the matches were important to you, try downloading older versions of the maps from https://resource.openra.net/maps/?mod=hv&format=any&sort_by=latest&with_problems=show&players= or load the game in the previous version.
