### ISSUE TITLE
Dark teleportation animation

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#522]
If a building is sold while being powered down, the teleportation animation inherits shadow palette.

![sell](https://user-images.githubusercontent.com/17529329/150774769-71e6890e-5a07-429f-a15b-5af241552eff.gif)

**Comment by GraionDilach** [comment]
This needs to be discussed on Discord/Matrix for sure, because I'm not sure if this is a bug.

The real question is when should the building start consuming power - when it is placed or when the animation finishes. If the former, then this is only a visual issue and the animation should ignore lighting overlays. If the latter then we should disable the lowpower condition with the WithMakeAnimation trait and this is a functional change.
