### ISSUE TITLE
Air transport units cannot load pods if a vehicle is already loaded.

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#523]
As title says:

![carryall](https://user-images.githubusercontent.com/17529329/150775304-817dfdb9-137a-4db5-a762-2d4a312424cb.gif)

**Comment by Mailaender** [comment]
This is because

```salt
	Carryall:
		LocalOffset: 0,0,200
```

adds some height, which, I think, makes sense.

**Comment by Dzierzan** [comment]
Yeah, setting it to 0,0,0 "fixes" the issue, but then it looks a bit bad for offsets.

**Comment by Dzierzan** [comment]
That's not a solution.

**Comment by nmoskopp** [comment]
I think https://github.com/OpenHV/OpenHV/commit/c56e39a68f0cc2e042f945112fa5f0a524901ad5 looks a lot like the game has to suffer because of engine limitations. Having a wrong cursor is annoying – but not being able to move pods or tanks changes the game balance a lot! If no pod transport is available, then there exists no way to transport an engineer on an island, since naval transport units do not exist (yet).

**Comment by Mailaender** [comment]
Depends on https://github.com/OpenRA/OpenRA/pull/20534.
