### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by ItsJony** [OpenHV/OpenHV#536]
This was a fresh installation of version 20220128.
There were multiple attempts to launch the game but only gave me an fatal error message.
I checked the FAQ and my latest exception log and didn't see anything mentioned about my error on the FAQ.
So, help would be greatly appreciated :)
[exception-2022-02-21T013427Z.log](https://github.com/OpenHV/OpenHV/files/8105563/exception-2022-02-21T013427Z.log)

**Comment by Dzierzan** [comment]
Hi. Install the previous version and then launch the game. You should see the welcome window, close it. Now uninstall that version and install the latest one. It should be working fine.

That welcome window crashes the game. If you close it in the previous one, it won't show up in the next versions. I believe it was already fixed in the master branch.

**Comment by Mailaender** [comment]
I crated a new https://github.com/OpenHV/OpenHV/releases/tag/20220221 that does not crash.
