### ISSUE TITLE
Make miners automatically seek nearest resource upon spawning

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#609]

**Comment by Mailaender** [comment]
I already thought about it and didn't want to make the game play itself. We will go with https://github.com/OpenHV/OpenHV/issues/590 instead.

**Comment by nmoskopp** [comment]
Whenever you have a game mechanic where a simple automation would make the game “play itself”, not automating it results in useless busywork for players (e.g. grinding enemies and boring resource collection), making games more repetitive and less fun (and in this case: definitely more frustrating) than they have to be.

IMO an “idle miners” button as proposed in https://github.com/OpenHV/OpenHV/issues/590 is unlikely to make the gameplay more frustrating as miners always spawn either at the storage building or at the main base AFAIK, (even when bought via trade platform a miner appears at the main base if a player has one, which is a bit weird).

I have a few more examples beyond the other OpenRA resource collectors:

* The roguelike Dungeon Crawl Stone Soup has both an “autoexplore” (go to an unexplored area) and an “autofight” (hit closest enemy) key binding by default. Yet, using these two will not get players very far, since this design choice forces the developers to avoid repetitive gameplay.
* In the RTS game Warzone 2100 units assigned to a commander can have a stance which makes them retreat to a repair building at low health and join the battle fully repaired, targeting whatever the commander targets. This makes gameplay more stratetic and tactics such as attacking the rear of an enemy army to hunt down damaged units viable.
* In the RTS game Liberation Circuit harvesters return to base by when they get damaged during harvesting. It was a very small change I added to the state machine for the default harvester script that massively improved gameplay – as faster harvesters (units can be put together by players in the game) could survive more easily.

**Comment by Mailaender** [comment]
We are inspired by Starcraft and Age of Empires in that regard.

**Comment by GraionDilach** [comment]
> * In the RTS game Warzone 2100 units assigned to a commander can have a stance which makes them retreat to a repair building at low health and join the battle fully repaired, targeting whatever the commander targets. This makes gameplay more strategic and tactics such as attacking the rear of an enemy army to hunt down damaged units viable.

So that's what the commander does! I never understood that unit. Thanks.

One thing to note to the initial issue: keep in miners that miners are mostly fire-and-forget already. Atleast with left-click-orders, I only have to target a resource stash once with the miner and it will go there and auto-deploy to the tower immediately (although in this case I'd actually attempt to delay the EVA announcement of the tower ready after the tower is built instead of the deploy start). The actual resource gain is done through the deliverers which are different units and are already automated to continue their job when they are idling.

**Comment by nmoskopp** [comment]
> We are inspired by Starcraft and Age of Empires in that regard.

I have little knowledge about Starcraft, but regarding Age of Empires, your assertion looks like cargo-culting to me – in AoE, villagers can be assigned different resource-gathering tasks like lumberjack, miner or hunter. What kind of task a villager is assigned to is actually a gameplay-relevant choice, as the game contains different resources. In contrast, OpenHV has exactly one resource.

**Comment by GraionDilach** [comment]
This is comparable to the aforementioned Warzone 2100 as well though where builders need to be explicitly sent to build an oil derrick (and need to take care of their refinery limits). Yes, OpenHV needs a separate unit compared to Warzone 2100, but there's no artificial 4-towers-vs-1-storage limitation and in both systems you get periodical money automatically after a you've got the tower/derrick built (with OpenHV using longer periods and bigger deliveries instead of the more constant flow).

**Comment by nmoskopp** [comment]
> This is comparable to the aforementioned Warzone 2100 as well though where builders need to be explicitly sent to build an oil derrick

Nope, Warzone 2100 is very different from OpenHV here, as tasking a builder with building an oil derrick deprives the player of the opportunity of doing something else at the same time. Especially in the early game, players have to choose carefully – similarly to the OpenHV choice of building a pod factory or a storage first in the early game.

It can help to try to look at it from the perspective of “does the player have a meaningful choice here?” instead of “do the units look superficially similar?”. In the OpenHV case, there is almost no meaningful choice compared to Warzone 2100, Age of Empires or even Command & Conquer: Red Alert – which features maps in which players can collect diamonds for more money that are further away from their starting position (i.e. a risk-reward play).
