### ISSUE TITLE
Transports with a mix of pods do not move close enough that all pods can shoot when given attack order

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#623]
To reproduce:
1. Put a rocket pod in a transport.
2. Put a sniper in the same transport.
3. Order the transport to attack a building that is out of range.
4. Verify that only the sniper attacks the building when the transport stops.

**Comment by nmoskopp** [comment]
Compare this to Mammoth tanks, which do use their main guns despite having rockets.

**Comment by GraionDilach** [comment]
Notsure what to suggest here. If you bring the transport closer to the target, the rocket pod will also start firing alongside the sniper pod. The "issue" is that the transport stops going closer to a target when any of it's passengers is in firing range.

YR worked this around with it's Battle Fortress having the omnicrusher AI - the unit itself always attempted to outright crush the target, which ensured it'll get the target into it's occupiers' firing range. YR players always found that problematic because it made kiting horrible, especially with the BFRT's lack of agility thrown to the mix.

IIRC overriding autotarget ranges can ensure that the Transport keeps a closer distance than the sniper pod's range, but it's been a while I've toyed with that.

**Comment by nmoskopp** [comment]
> The "issue" is that the transport stops going closer to a target when any of it's passengers is in firing range.

Suggestion: Stop moving when _all_ passengers are in firing range.
